### PR TITLE
added alphabetical and colorful printing

### PR DESCRIPTION
**Pull request by denizural**
This was already in my TODO list for a while. When @chrisdane asked for it I decided to give it a try:

### Before:
image

image

### After: 
image

image

### CODE REVIEW

**Comment by pgierz** [comment]
Shouldn't the version numbers also be ordered?

**Comment by denizural** [comment]
@pgierz, this is a good point. Let me do that. Thanks for the heads up

**Comment by denizural** [comment]
Looks better now (compared to the first commit): 

image

**Review by mandresm — APPROVED** [review]
Nice job Deniz! :) I tested and it seems to work perfectly. It looks REALLY cool :)

**Pull request merged**
